// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_chessboardutilities.cpp"
#include "EWIEGA46WW/moc_figureback.cpp"
#include "EWIEGA46WW/moc_tileback.cpp"
#include "EWIEGA46WW/moc_tilesfigureshandler.cpp"
